/* gtk+3.0.vapi generated by valac 0.26.2, do not modify. */

[CCode (cheader_filename = "MainWindow.h")]
public class Button : GLib.Object {
	public Button ();
	public Button.from_stock (string stock_id);
	public Button.with_label (string label);
}
